version: '3.8'
services:
  odoo:
    image: odoo:16.0
    networks:
      - odoo-network
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.odoo-http.rule=Host(`odoo.xample.net`)
        - traefik.http.routers.odoo-http.entrypoints=http
        - traefik.http.routers.odoo-http.middlewares=https-redirect
        - traefik.http.routers.odoo-https.rule=Host(`odoo.xample.net`)
        - traefik.http.routers.odoo-https.entrypoints=https
        - traefik.http.routers.odoo-https.tls=true
        - traefik.http.routers.odoo-https.tls.certresolver=le
        - traefik.http.services.odoo.loadbalancer.server.port=8069
    environment:
    - HOST=db
    - USER=odoo
    - PASSWORD=myodoo
  db:
    image: postgres:15
    networks:
      - odoo-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo

networks:
  odoo-network:
  traefik-public:
    external: true


    # 63r5-zfqm-wrhw